springapp:
  image: geethar27/springapp:latest
  container_name: springapp
  depends_on:
    - clicknbuy-db
  restart: always
  ports:
    - "80:80"
  networks:
    - app-network
  environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://clicknbuy-db:3306/clicknbuy?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL8Dialect
      
      EMAIL_USERNAME: geethar272003@gmail.com
      EMAIL_PASSWORD: ozopfngqzxumganao   # Gmail App password ONLY

      CLOUDINARY_URL: cloudinary://289133591992525:7DCImx3QCwjki1LTbEWDz4mlA0s@djkyoabl5

      TZ: Asia/Kolkata
