version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jspgram
      MYSQL_ROOT_HOST: '%'
      TZ: Asia/Kolkata
    ports:
      - "3306:3306"
    networks:
      - app-network

  springapp:
    image: geethar27/springapp:latest
    container_name: springapp
    depends_on:
      - mysql-db
    restart: always
    ports:
      - "80:80"
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/jspgram
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      TZ: Asia/Kolkata

networks:
  app-network:
    driver: bridge
